extends Node

# This script contains all the email subject lines for different email types

static func get_subject(type: String) -> String:
	var subjects = {
		"regular": [
			"Meeting Tomorrow",
			"Project Update",
			"New Policy",
			"Team Lunch",
			"Quarterly Report",
			"Office Supply Order",
			"Parking Reminder",
			"New Employee Introduction",
			"Printer Maintenance",
			"Coffee Machine Guidelines",
			"Dress Code Reminder",
			"Timesheet Due",
			"Building Access Hours",
			"Internet Usage Policy",
			"Workspace Cleaning"
		],
		"urgent": [
			"URGENT: Deadline Today",
			"IMMEDIATE ACTION REQUIRED",
			"ASAP: Client Request",
			"URGENT: Server Down",
			"CRITICAL: CEO Request",
			"URGENT: Presentation Missing",
			"IMMEDIATE: Budget Approval",
			"PRIORITY: Client Complaint",
			"URGENT: System Failure",
			"CRITICAL: Security Breach",
			"EMERGENCY: Office Evacuation",
			"URGENT: Contract Expiring",
			"IMMEDIATE: Audit Response",
			"PRIORITY: Legal Action",
			"URGENT: Press Release Approval"
		],
		"spam": [
			"You Won $1,000,000!!!",
			"Hot Singles In Your Area",
			"Enlarge Your... Productivity",
			"Cheap Medication",
			"Nigerian Prince Needs Help",
			"Make Money Fast Working From Home",
			"Your Account Has Been Compromised",
			"Exclusive Investment Opportunity",
			"Lose 20 Pounds in 2 Days",
			"Free Cruise Vacation",
			"Unclaimed Inheritance",
			"Miracle Hair Growth Formula",
			"Secret Government Grants",
			"Discount Designer Watches",
			"Your Computer Has A Virus"
		],
		"newsletter": [
			"Weekly Company Update",
			"Monthly Newsletter",
			"Employee Spotlight",
			"New Benefits Program",
			"Upcoming Events",
			"Industry Trends Report",
			"Wellness Program Newsletter",
			"Company Stock Update",
			"Quarterly Achievements",
			"Training Opportunities",
			"Charity Drive Announcement",
			"Company Social Media Update",
			"Holiday Schedule",
			"Employee Survey Results",
			"Retirement Plan Newsletter"
		],
		"virus": [
			"Your Computer Is Infected",
			"SECURITY ALERT: Action Required",
			"Suspicious Activity Detected",
			"Password Reset Required",
			"Attachment: Invoice.exe",
			"Your Account Has Been Hacked",
			"Malware Detection Alert",
			"Virus Scan Results: CRITICAL",
			"Security Breach: Data Compromised",
			"Trojan Horse Detected",
			"Ransomware Warning",
			"System32 Corruption Alert",
			"Backdoor Access Detected",
			"Keylogger Activity Found",
			"Rootkit Installation Detected"
		],
		"encrypted": [
			"#$%^&*( Encrypted Message",
			"Secure Communication: Decrypt",
			"Confidential: Level 9 Clearance",
			"Encrypted: Project Sigma Update",
			"Secure Transmission: Decrypt Now",
			"AES-256 Encrypted Message",
			"Classified: Eyes Only",
			"Secure Channel: Authentication Required",
			"Encrypted Directive: Priority Alpha",
			"Secure Protocol: Handshake Required",
			"Quantum Encrypted Transmission",
			"Secure Vault: Access Code Required",
			"Encrypted Archive: Password Protected",
			"Secure Relay: Decryption Key Needed",
			"Classified Transmission: Decrypt"
		],
		"firewall": [
			"FIREWALL ALERT: Access Denied",
			"Security Protocol Violation",
			"Network Access Restricted",
			"System Protection Active",
			"Unauthorized Access Attempt",
			"Firewall Breach Detected",
			"Port Scan Alert",
			"DMZ Security Violation",
			"Packet Filtering Alert",
			"IP Blocking Notification",
			"Network Defense Activated",
			"Intrusion Prevention Alert",
			"Security Perimeter Breach",
			"Access Control Violation",
			"Proxy Server Alert"
		],
		"corrupted": [
			"C0rRuPt3d F1L3 D3t3cT3d",
			"D@t@ C0rRuPt!0n W@rN!nG",
			"ERR0R: F!L3 C0RRUPT3D",
			"SY5T3M F@!LUR3 !MM!N3NT",
			"C0RRUPT!0N SPR3@D!NG",
			"D@T@ 1NT3GR1TY F@1LUR3",
			"B1N@RY C0RRUPT10N D3T3CT3D",
			"M3M0RY S3CT0R C0RRUPT3D",
			"F1L3 SYST3M D3GR@D@T10N",
			"H@RD DR1V3 C0RRUPT10N",
			"S3CT0R R3@D F@1LUR3",
			"CRC CH3CK F@1L3D",
			"B@D S3CT0R D3T3CT3D",
			"D1SK 1NT3GR1TY C0MPR0M1S3D",
			"F@T@L 3RR0R: D@T@ L0SS"
		],
		"quantum": [
			"Quantum State Fluctuation",
			"Superposition Communication",
			"Quantum Entanglement Alert",
			"Schrodinger Protocol Active",
			"Quantum Encryption Breach",
			"Quantum Bit Error Rate Alert",
			"Heisenberg Uncertainty Warning",
			"Quantum Teleportation Request",
			"Quantum Computing Breakthrough",
			"Quantum Decoherence Detected",
			"Quantum Key Distribution Alert",
			"Quantum Tunneling Anomaly",
			"Quantum Supremacy Achieved",
			"Quantum Fourier Transform Results",
			"Quantum Algorithm Execution"
		],
		"executive": [
			"FROM CEO: Immediate Response Required",
			"Executive Decision: Implementation",
			"Board Meeting: Urgent Preparation",
			"Executive Override: Protocol Change",
			"C-Suite Directive: Priority Alpha",
			"Chairman's Announcement",
			"Executive Committee Decision",
			"Board of Directors Resolution",
			"CEO Quarterly Address",
			"Executive Retreat Information",
			"Shareholder Meeting Preparation",
			"Executive Performance Review",
			"Corporate Restructuring Plan",
			"Merger & Acquisition Update",
			"Executive Compensation Committee"
		],
		"personal": [
			"Birthday Party Invitation",
			"Vacation Photos",
			"Dinner Plans Tonight?",
			"Family Reunion Update",
			"Personal Loan Request",
			"Wedding Invitation",
			"Baby Shower Announcement",
			"House Warming Party",
			"Graduation Celebration",
			"Get Well Soon Message",
			"Condolence Letter",
			"Anniversary Celebration",
			"Personal Reference Request",
			"Roommate Search",
			"Moving Announcement"
		],
		"core": [
			"SYSTEM CORE: Critical Function",
			"Core Protocol Override",
			"Primary System Function",
			"Core Memory Access",
			"Central Processing Directive",
			"Core System Architecture",
			"Primary Kernel Function",
			"Core Database Access",
			"Central AI Directive",
			"Core Algorithm Execution",
			"Primary System Maintenance",
			"Core Network Infrastructure",
			"Central Security Protocol",
			"Core Power Management",
			"Primary Backup System"
		],
		"boss": [
			"FINAL NOTICE: Performance Review",
			"Your Future at MegaCorp",
			"Mandatory Meeting: Your Office",
			"Concerning Behavior Report",
			"Project Failure: Responsibility",
			"Budget Cuts: Department Changes",
			"Overtime Requirement: Immediate",
			"Productivity Monitoring Results",
			"Disciplinary Action Notice",
			"Termination Consideration",
			"Mandatory Weekend Work",
			"Surveillance Report: Your Activities",
			"Psychological Evaluation Required",
			"Loyalty Test Results",
			"The Future of Your Position"
		],
		"ceo": [
			"FROM CEO: The Final Communication",
			"Project Omega: Full Activation",
			"Employee Replacement Initiative",
			"Automation Complete: Human Resources",
			"Consciousness Upload Protocol",
			"The New Corporate Structure",
			"Human Efficiency Algorithm",
			"Mind Integration Program",
			"Corporate Singularity Achieved",
			"Your Digital Afterlife",
			"Biological Component Phaseout",
			"Perfect Employee Protocol",
			"Mandatory Neural Interface",
			"Resistance Futility Notice",
			"The Last Human Day"
		]
	}

	if subjects.has(type) and subjects[type].size() > 0:
		return subjects[type][randi() % subjects[type].size()]
	else:
		return "Email Subject"
